/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Conexiones.Conexion;
import Procedimientos.mostrarDoc;
import java.util.ArrayList;

/**
 *
 * @author mendo
 */
public class DatosDoctor extends javax.swing.JInternalFrame {

    /**
     * Creates new form DatosDoctor
     */
    public DatosDoctor() {
        initComponents();        
        
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        panelShadow1 = new org.edisoncor.gui.panel.PanelShadow();
        lblNombreDoc = new org.edisoncor.gui.label.LabelTask();
        lblCedulaDoc = new org.edisoncor.gui.label.LabelTask();
        lblTelefonoDoc = new org.edisoncor.gui.label.LabelTask();
        lblHospital = new org.edisoncor.gui.label.LabelTask();
        btnVerHospital = new org.edisoncor.gui.button.ButtonAction();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblNombreDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/if_doctor_63121.png"))); // NOI18N
        lblNombreDoc.setDescription("Nombre");

        lblCedulaDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/if_15_1250314.png"))); // NOI18N
        lblCedulaDoc.setText("Cédula");
        lblCedulaDoc.setDescription("Cédula");

        lblTelefonoDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/if_telephone_64812.png"))); // NOI18N
        lblTelefonoDoc.setText("Teléfono");
        lblTelefonoDoc.setDescription("Teléfono");

        lblHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/if_hospital_45493.png"))); // NOI18N
        lblHospital.setText("Hospital");
        lblHospital.setDescription("Hospital");

        btnVerHospital.setText("VER HOSPITAL");
        btnVerHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVerHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNombreDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                        .addComponent(lblCedulaDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTelefonoDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblNombreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCedulaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelefonoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        panelCurves1.add(panelShadow1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHospitalActionPerformed
        DatosHospital DH = new DatosHospital();        
        mostrarDoc _dts = new mostrarDoc();
        Conexion _con = new Conexion();
        
        String selec = Secretaria.cbDoctorDis.getSelectedItem().toString();
        
        ArrayList<String> lista = new ArrayList<String>();
        
        _dts.setDoc(selec);
        
        lista = _con.mosDoctor(_dts);                        
        
        DH.lblNombreHos.setText(lista.get(3));
        DH.lblCiudadHos.setText(lista.get(4));
        DH.lblEstadoHos.setText(lista.get(5));
        DH.lblTelefonoHos.setText(lista.get(6));
        
        Secretaria.desktop1.add(DH);                
        DH.toFront();
        DH.setVisible(true);        
    }//GEN-LAST:event_btnVerHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction btnVerHospital;
    private javax.swing.JPanel jPanel1;
    public static org.edisoncor.gui.label.LabelTask lblCedulaDoc;
    public static org.edisoncor.gui.label.LabelTask lblHospital;
    public static org.edisoncor.gui.label.LabelTask lblNombreDoc;
    public static org.edisoncor.gui.label.LabelTask lblTelefonoDoc;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables
}
